import type { Octokit } from "octokit";
import {
  parseStruktrConfig,
  substituteBackendUrl,
  type StruktrConfig,
} from "./struktrConfig.js";

export const COMMENT_MARKER = "<!-- struktr-interactive-previews -->";

export interface PrRef {
  owner: string;
  repo: string;
  number: number;
  headSha: string;
  labels: string[];
}

export interface OrchestratorClient {
  createSession(req: {
    prHash: string;
    device: string;
    apkUrl: string;
    appId?: string;
    backendUrl?: string;
  }): Promise<{ id: string; playerUrl: string; status: string }>;
}

export function makeOrchestratorClient(
  baseUrl: string,
  apiToken: string,
): OrchestratorClient {
  return {
    async createSession(req) {
      const res = await fetch(`${baseUrl}/api/sessions`, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: `Bearer ${apiToken}`,
        },
        body: JSON.stringify(req),
      });
      if (!res.ok) {
        const body = await res.text();
        throw new Error(`orchestrator ${res.status}: ${body}`);
      }
      return res.json() as Promise<{ id: string; playerUrl: string; status: string }>;
    },
  };
}

export async function fetchStruktrConfig(
  octokit: Octokit,
  pr: PrRef,
): Promise<StruktrConfig> {
  try {
    const res = await octokit.rest.repos.getContent({
      owner: pr.owner,
      repo: pr.repo,
      path: ".struktr.yml",
      ref: pr.headSha,
    });
    const data = res.data as { content?: string; encoding?: string };
    const raw = data.content
      ? Buffer.from(data.content, (data.encoding as BufferEncoding) ?? "base64").toString("utf8")
      : null;
    return parseStruktrConfig(raw);
  } catch (err) {
    if ((err as { status?: number }).status === 404) return parseStruktrConfig(null);
    throw err;
  }
}

/** Find the pre-signed download URL of the newest artifact named
 * `artifactName` produced by a workflow run for the PR's head SHA.
 * Returns null when CI hasn't produced it (yet). */
export async function findArtifactUrl(
  octokit: Octokit,
  pr: PrRef,
  artifactName: string,
): Promise<string | null> {
  const runs = await octokit.rest.actions.listWorkflowRunsForRepo({
    owner: pr.owner,
    repo: pr.repo,
    head_sha: pr.headSha,
    per_page: 30,
  });
  for (const run of runs.data.workflow_runs) {
    const artifacts = await octokit.rest.actions.listWorkflowRunArtifacts({
      owner: pr.owner,
      repo: pr.repo,
      run_id: run.id,
    });
    const hit = artifacts.data.artifacts.find(
      (a) => a.name === artifactName && !a.expired,
    );
    if (hit) {
      // Resolve the time-limited unauthenticated redirect target so the
      // orchestrator can download without a GitHub token.
      const dl = await octokit.request(
        "GET /repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}",
        {
          owner: pr.owner,
          repo: pr.repo,
          artifact_id: hit.id,
          archive_format: "zip",
          request: { redirect: "manual" },
        },
      ).catch((err: { status?: number; response?: { headers?: Record<string, string> } }) => {
        // Octokit surfaces the 302 as an error in some transports; the
        // location header is the value we want either way.
        if (err.status === 302 && err.response?.headers?.location) {
          return { headers: { location: err.response.headers.location } };
        }
        throw err;
      });
      const location = (dl as { headers?: { location?: string }; url?: string }).headers
        ?.location ?? (dl as { url?: string }).url;
      if (location) return location;
    }
  }
  return null;
}

export function buildCommentBody(
  sessions: { device: string; playerUrl: string }[],
  ctx: { headSha: string; backendUrl?: string; pending?: boolean },
): string {
  const lines = [
    COMMENT_MARKER,
    "## 📱 Interactive app preview",
    "",
    `Commit \`${ctx.headSha.slice(0, 7)}\`${ctx.backendUrl ? ` · backend [${ctx.backendUrl}](${ctx.backendUrl})` : ""}`,
    "",
  ];
  if (ctx.pending) {
    lines.push("⏳ Waiting for CI to produce the APK artifact — previews will appear here when it lands.");
  } else {
    lines.push("| Device | Session |", "|---|---|");
    for (const s of sessions) {
      lines.push(`| ${s.device} | [▶ Open interactive preview](${s.playerUrl}) |`);
    }
    lines.push("", "_Sessions boot in ~60-90s and idle out after 30 min. Outside business hours the pool sleeps._");
  }
  lines.push("", "_Generated by [struktr](https://github.com/magucc/struktr)._");
  return lines.join("\n");
}

export async function upsertComment(
  octokit: Octokit,
  pr: PrRef,
  body: string,
): Promise<void> {
  const comments = await octokit.rest.issues.listComments({
    owner: pr.owner,
    repo: pr.repo,
    issue_number: pr.number,
    per_page: 100,
  });
  const existing = comments.data.find((c) => c.body?.startsWith(COMMENT_MARKER));
  if (existing) {
    await octokit.rest.issues.updateComment({
      owner: pr.owner,
      repo: pr.repo,
      comment_id: existing.id,
      body,
    });
  } else {
    await octokit.rest.issues.createComment({
      owner: pr.owner,
      repo: pr.repo,
      issue_number: pr.number,
      body,
    });
  }
}

/** Full pickup: config → artifact → sessions per device → PR comment. */
export async function handlePreviewRequest(
  octokit: Octokit,
  orchestrator: OrchestratorClient,
  pr: PrRef,
): Promise<"skipped" | "pending" | "done"> {
  const cfg = await fetchStruktrConfig(octokit, pr);
  if (!pr.labels.includes(cfg.label)) return "skipped";

  const backendUrl = substituteBackendUrl(cfg.backendUrl, {
    number: pr.number,
    sha: pr.headSha,
  });

  const apkUrl = await findArtifactUrl(octokit, pr, cfg.artifact);
  if (!apkUrl) {
    await upsertComment(octokit, pr, buildCommentBody([], { headSha: pr.headSha, backendUrl, pending: true }));
    return "pending";
  }

  const sessions: { device: string; playerUrl: string }[] = [];
  for (const device of cfg.devices) {
    const s = await orchestrator.createSession({
      prHash: pr.headSha.slice(0, 7),
      device,
      apkUrl,
      appId: cfg.appId,
      backendUrl,
    });
    sessions.push({ device, playerUrl: s.playerUrl });
  }

  await upsertComment(octokit, pr, buildCommentBody(sessions, { headSha: pr.headSha, backendUrl }));
  return "done";
}
