#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "struktr preview-service — VM provisioning"

# ── Stage 1: create the VM ────────────────────────────────────────────────
stage "Create a KVM-capable VM"
say "The emulator needs hardware virtualization (KVM). Two good options:"
say ""
step "AWS (use this if burning Activate credits): EC2 → Launch instance."
note "  Type: m8i.xlarge (4 vCPU/16GB, ~2 sessions) or m8i.2xlarge (8 vCPU/32GB, ~4-6)."
note "  Only C8i/M8i/R8i families support nested virt (KVM) on virtual instances."
note "  AMI: Ubuntu Server 24.04 LTS x86_64. Storage: 60GB gp3."
note "  Security group: allow 22 (your IP), 80, 443 (world)."
step "Azure alternative: Create VM → D8s_v5, Ubuntu 24.04, SECURITY TYPE: Standard"
note "  (NOT Trusted Launch — it disables nested virtualization). Ports 22/80/443."
open_url "https://console.aws.amazon.com/ec2/home#LaunchInstances:"
pause "Press Enter once the VM is running."
ask VM_SSH_USER "SSH user (ubuntu for AWS Ubuntu AMIs, azureuser for Azure):"
ask VM_HOST "Public IP or hostname of the VM:"
write_env VM_SSH_USER "$VM_SSH_USER"
write_env VM_HOST "$VM_HOST"

# ── Stage 2: KVM + Docker on the VM ───────────────────────────────────────
stage "Verify KVM and install Docker"
say "Run these on the VM (ssh $VM_SSH_USER@$VM_HOST):"
say ""
note '  sudo apt-get update && sudo apt-get install -y cpu-checker && sudo kvm-ok'
note '  # must print "KVM acceleration can be used" — if not, wrong instance type'
note '  curl -fsSL https://get.docker.com | sudo sh'
note '  sudo usermod -aG docker $USER && exit   # re-login to pick up the group'
say ""
if confirm "Run these over SSH from here now?"; then
  ssh -o StrictHostKeyChecking=accept-new "$VM_SSH_USER@$VM_HOST" \
    'sudo apt-get update -qq && sudo apt-get install -y -qq cpu-checker && sudo kvm-ok && curl -fsSL https://get.docker.com | sudo sh && sudo usermod -aG docker $USER'
  say "Done — KVM verified and Docker installed."
else
  pause "Run them manually, then press Enter."
fi

# ── Stage 3: build the emulator image ─────────────────────────────────────
stage "Build the emulator container image"
say "We build Google's emulator container (WebRTC-enabled) on the VM:"
say ""
note '  git clone https://github.com/google/android-emulator-container-scripts.git'
note '  cd android-emulator-container-scripts'
note '  python3 -m venv venv && . venv/bin/activate && pip install -e .'
note '  emu-docker create stable "P google_apis x86_64"   # picks latest stable emulator + API img'
note '  docker tag $(docker images -q | head -1) struktr-emulator:latest'
say ""
warn "This downloads several GB and takes 10-20 min."
if confirm "Run over SSH from here now?"; then
  ssh "$VM_SSH_USER@$VM_HOST" 'git clone -q https://github.com/google/android-emulator-container-scripts.git || true; cd android-emulator-container-scripts && python3 -m venv venv && . venv/bin/activate && pip install -q -e . && yes | emu-docker create stable "P google_apis x86_64" && docker tag $(docker images --format "{{.Repository}}:{{.Tag}}" | grep -m1 emulator) struktr-emulator:latest && docker images | head -5'
else
  pause "Run manually on the VM, then press Enter."
fi

# ── Stage 4: DNS + domain ─────────────────────────────────────────────────
stage "Point a domain at the VM"
say "The player needs a domain with TLS (Caddy auto-provisions certificates)."
step "In your DNS provider, add an A record, e.g. app-preview.kju.ai → $VM_HOST"
ask PREVIEW_DOMAIN "Domain you configured (e.g. app-preview.kju.ai):"
write_env PREVIEW_DOMAIN "$PREVIEW_DOMAIN"
note "DNS may take a few minutes to propagate; Caddy retries automatically."

# ── Stage 5: secrets + pool config ────────────────────────────────────────
stage "Generate service secrets and pool config"
SESSION_JWT_SECRET=$(openssl rand -hex 32)
ORCHESTRATOR_API_TOKEN=$(openssl rand -hex 32)
write_env SESSION_JWT_SECRET "$SESSION_JWT_SECRET"
write_env ORCHESTRATOR_API_TOKEN "$ORCHESTRATOR_API_TOKEN"
write_env PUBLIC_URL "https://$PREVIEW_DOMAIN"
ask POOL_HOURS "Business hours for the pool (default 08:00-18:30):"
write_env POOL_HOURS "${POOL_HOURS:-08:00-18:30}"
ask POOL_TZ "Timezone (default Europe/Amsterdam):"
write_env POOL_TZ "${POOL_TZ:-Europe/Amsterdam}"
say "The GitHub App / CI needs to reach the orchestrator:"
set_secret ORCHESTRATOR_API_TOKEN "$ORCHESTRATOR_API_TOKEN"
set_var ORCHESTRATOR_URL "https://$PREVIEW_DOMAIN"

# ── Stage 6: deploy the control plane ─────────────────────────────────────
stage "Deploy orchestrator + Caddy"
say "Copy the service to the VM and start it:"
say ""
note "  rsync -a --exclude node_modules preview-service .env $VM_SSH_USER@$VM_HOST:~/struktr/"
note "  ssh $VM_SSH_USER@$VM_HOST 'cd ~/struktr/preview-service/docker && docker compose up -d --build'"
say ""
if confirm "Run from here now (needs rsync)?"; then
  rsync -a --exclude node_modules "$(dirname "$0")/.." "$ENV_FILE" "$VM_SSH_USER@$VM_HOST:~/struktr/"
  ssh "$VM_SSH_USER@$VM_HOST" 'cd ~/struktr/preview-service/docker && docker compose up -d --build'
else
  pause "Run manually, then press Enter."
fi

# ── Stage 7: business-hours VM scheduler ──────────────────────────────────
stage "Schedule the VM (business hours only)"
say "The orchestrator refuses new sessions outside POOL_HOURS, but stopping the"
say "VM itself is what saves money. On AWS:"
step "EventBridge Scheduler → Create schedule → cron(30 18 ? * MON-FRI *) → StopInstances"
step "and a second schedule cron(45 7 ? * MON-FRI *) → StartInstances (times in $POOL_TZ)."
open_url "https://console.aws.amazon.com/scheduler/home"
note "Azure: use Auto-shutdown (portal, VM blade) + an Automation start schedule."
warn "Skip this stage entirely if you'd rather leave the VM always-on for now."
pause "Press Enter when done (or skipped)."

# ── Stage 8: smoke test ───────────────────────────────────────────────────
stage "Smoke test"
say "Create a test session against the deployed orchestrator:"
say ""
note "  curl -s -X POST https://$PREVIEW_DOMAIN/api/sessions \\"
note "    -H \"Authorization: Bearer \$ORCHESTRATOR_API_TOKEN\" -H 'Content-Type: application/json' \\"
note "    -d '{\"prHash\":\"smoke\",\"device\":\"pixel-7\",\"apkUrl\":\"<any-debug-apk-url>\"}'"
say ""
say "The response contains a playerUrl — open it in a browser and you should"
say "see the emulator boot and become clickable within ~60-90s."
if confirm "Open the health endpoint now?"; then
  open_url "https://$PREVIEW_DOMAIN/healthz"
fi

finish
