#!/usr/bin/env bash
# Publish captured screenshots: push PNGs to the archive branch of the calling
# repo, write a gallery to the job summary, and (in PR context, when enabled)
# upsert a sticky gallery comment on the PR.
#
# Env: GH_TOKEN, ARCHIVE_BRANCH, COMMENT_ENABLED, HEAD_SHA,
#      PR_NUMBER (empty outside PR context),
#      GITHUB_REPOSITORY, GITHUB_RUN_ID, GITHUB_REF_NAME (provided by Actions)
set -euo pipefail

MARKER="<!-- struktr-preview-screenshots -->"
REPO="${GITHUB_REPOSITORY}"
CLONE_URL="https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git"
ARCHIVE_DIR="$(mktemp -d)"

if [ -n "${PR_NUMBER:-}" ]; then
  DEST="pr-${PR_NUMBER}/${GITHUB_RUN_ID}"
  CONTEXT_LINE="PR #${PR_NUMBER}"
else
  DEST="branch-$(echo "${GITHUB_REF_NAME:-unknown}" | tr '/' '-')/${GITHUB_RUN_ID}"
  CONTEXT_LINE="branch \`${GITHUB_REF_NAME:-unknown}\`"
fi

shopt -s nullglob
shots=(screenshots/*.png)
if [ ${#shots[@]} -eq 0 ]; then
  echo "::error::No screenshots found in screenshots/ — flow ran but captured nothing."
  exit 1
fi

if git clone --depth 1 --branch "$ARCHIVE_BRANCH" "$CLONE_URL" "$ARCHIVE_DIR" 2>/dev/null; then
  echo "Cloned existing $ARCHIVE_BRANCH branch."
else
  git init -b "$ARCHIVE_BRANCH" "$ARCHIVE_DIR"
  git -C "$ARCHIVE_DIR" remote add origin "$CLONE_URL"
fi

mkdir -p "$ARCHIVE_DIR/$DEST"
cp "${shots[@]}" "$ARCHIVE_DIR/$DEST/"

git -C "$ARCHIVE_DIR" add .
git -C "$ARCHIVE_DIR" \
  -c user.name="github-actions[bot]" \
  -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
  commit -m "screenshots: ${CONTEXT_LINE} run ${GITHUB_RUN_ID}"
git -C "$ARCHIVE_DIR" push origin "$ARCHIVE_BRANCH"

RAW_BASE="https://raw.githubusercontent.com/${REPO}/${ARCHIVE_BRANCH}/${DEST}"
RUN_URL="${GITHUB_SERVER_URL:-https://github.com}/${REPO}/actions/runs/${GITHUB_RUN_ID}"

BODY="${MARKER}
## 📱 Preview screenshots

Android emulator · ${CONTEXT_LINE} · commit \`${HEAD_SHA:0:7}\` · [run](${RUN_URL})

| Step | Android |
|---|---|"

for shot in "${shots[@]}"; do
  name="$(basename "$shot" .png)"
  BODY="${BODY}
| \`${name}\` | <img src=\"${RAW_BASE}/${name}.png\" width=\"250\"> |"
done

BODY="${BODY}

_Generated by [struktr](https://github.com/magucc/struktr)._"

echo "$BODY" >> "$GITHUB_STEP_SUMMARY"

if [ -n "${PR_NUMBER:-}" ] && [ "${COMMENT_ENABLED}" = "true" ]; then
  EXISTING_ID="$(gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" --paginate \
    --jq ".[] | select(.body | startswith(\"${MARKER}\")) | .id" | head -n1 || true)"
  if [ -n "$EXISTING_ID" ]; then
    gh api -X PATCH "repos/${REPO}/issues/comments/${EXISTING_ID}" -f body="$BODY" >/dev/null
    echo "Updated existing gallery comment ${EXISTING_ID}."
  else
    gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" -f body="$BODY" >/dev/null
    echo "Posted new gallery comment."
  fi
fi
